from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import cv2
import numpy as np
import torch


CLASS_COLORS_BGR = {
    "top": (0, 255, 0),
    "pants": (255, 128, 0),
    "skirt": (255, 0, 255),
    "outwear": (0, 165, 255),
    "dress": (255, 0, 0),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Segment garments with SAM-HQ using YOLO detections as box prompts."
    )

    parser.add_argument(
        "--detections-json",
        type=str,
        required=True,
        help="Path to detections.json generated by predict_garments_yolo.py.",
    )
    parser.add_argument(
        "--sam-checkpoint",
        type=str,
        required=True,
        help="Path to SAM-HQ checkpoint, e.g. checkpoints/sam_hq/sam_hq_vit_h.pth.",
    )
    parser.add_argument(
        "--model-type",
        type=str,
        default="vit_h",
        choices=["vit_h", "vit_l", "vit_b"],
        help="SAM-HQ model type.",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="outputs/infer/samhq_garments",
        help="Output directory.",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cuda",
        help="Device: cuda or cpu.",
    )
    parser.add_argument(
        "--multimask-output",
        action="store_true",
        help="Use SAM multimask output. If enabled, the best score mask is selected.",
    )
    parser.add_argument(
        "--mask-alpha",
        type=float,
        default=0.45,
        help="Overlay alpha for masks.",
    )
    parser.add_argument(
        "--min-box-area",
        type=float,
        default=10.0,
        help="Skip detections with box area smaller than this value.",
    )

    return parser.parse_args()


def import_samhq():
    """
    Try common SAM-HQ / SAM import paths.

    Your environment may expose either:
    - segment_anything: sam_model_registry, SamPredictor
    - segment_anything_hq: sam_model_registry, SamPredictor

    This function keeps the script compatible with both.
    """
    try:
        from segment_anything import sam_model_registry, SamPredictor

        print("[INFO] Imported SAM from segment_anything")
        return sam_model_registry, SamPredictor
    except Exception as e1:
        print(f"[WARN] Failed to import from segment_anything: {e1}")

    try:
        from segment_anything_hq import sam_model_registry, SamPredictor

        print("[INFO] Imported SAM-HQ from segment_anything_hq")
        return sam_model_registry, SamPredictor
    except Exception as e2:
        print(f"[WARN] Failed to import from segment_anything_hq: {e2}")

    raise ImportError(
        "Cannot import SAM-HQ. Expected package with "
        "`sam_model_registry` and `SamPredictor`. "
        "Please check your SAM-HQ installation."
    )


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def save_json(data: dict[str, Any], path: Path) -> None:
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def ensure_uint8_mask(mask: np.ndarray) -> np.ndarray:
    if mask.dtype == np.bool_:
        return (mask.astype(np.uint8) * 255)
    if mask.max() <= 1:
        return (mask.astype(np.uint8) * 255)
    return mask.astype(np.uint8)


def bbox_area_xyxy(bbox: list[float]) -> float:
    x1, y1, x2, y2 = bbox
    return max(0.0, x2 - x1) * max(0.0, y2 - y1)


def clip_box_xyxy(
    bbox: list[float],
    width: int,
    height: int,
) -> np.ndarray:
    x1, y1, x2, y2 = bbox
    x1 = max(0.0, min(float(width - 1), float(x1)))
    y1 = max(0.0, min(float(height - 1), float(y1)))
    x2 = max(0.0, min(float(width - 1), float(x2)))
    y2 = max(0.0, min(float(height - 1), float(y2)))
    return np.array([x1, y1, x2, y2], dtype=np.float32)


def draw_box_label(
    image: np.ndarray,
    bbox_xyxy: list[float],
    label: str,
    color: tuple[int, int, int],
) -> None:
    x1, y1, x2, y2 = [int(round(v)) for v in bbox_xyxy]
    cv2.rectangle(image, (x1, y1), (x2, y2), color, 2)

    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.55
    thickness = 2

    (tw, th), baseline = cv2.getTextSize(label, font, font_scale, thickness)
    y_text_top = max(0, y1 - th - baseline - 4)
    y_text_bottom = y_text_top + th + baseline + 4

    cv2.rectangle(
        image,
        (x1, y_text_top),
        (x1 + tw + 6, y_text_bottom),
        color,
        -1,
    )
    cv2.putText(
        image,
        label,
        (x1 + 3, y_text_bottom - baseline - 2),
        font,
        font_scale,
        (255, 255, 255),
        thickness,
        cv2.LINE_AA,
    )


def apply_mask_overlay(
    overlay: np.ndarray,
    mask_bool: np.ndarray,
    color_bgr: tuple[int, int, int],
    alpha: float,
) -> np.ndarray:
    color_layer = np.zeros_like(overlay, dtype=np.uint8)
    color_layer[:, :] = color_bgr

    blended = cv2.addWeighted(overlay, 1.0, color_layer, alpha, 0)

    out = overlay.copy()
    out[mask_bool] = blended[mask_bool]
    return out


def get_best_mask(
    masks: np.ndarray,
    scores: np.ndarray | None,
) -> tuple[np.ndarray, float | None, int]:
    """
    masks:
      - shape [N, H, W] or [H, W]
    scores:
      - shape [N]
    """
    if masks.ndim == 2:
        score = float(scores[0]) if scores is not None and len(scores) > 0 else None
        return masks, score, 0

    if scores is None or len(scores) == 0:
        return masks[0], None, 0

    best_idx = int(np.argmax(scores))
    return masks[best_idx], float(scores[best_idx]), best_idx


def run(args: argparse.Namespace) -> None:
    detections_json = Path(args.detections_json)
    sam_checkpoint = Path(args.sam_checkpoint)
    output_dir = Path(args.output_dir)

    if not detections_json.exists():
        raise FileNotFoundError(f"detections_json not found: {detections_json}")

    if not sam_checkpoint.exists():
        raise FileNotFoundError(f"SAM-HQ checkpoint not found: {sam_checkpoint}")

    output_dir.mkdir(parents=True, exist_ok=True)

    masks_dir = output_dir / "masks"
    overlays_dir = output_dir / "overlays"
    masks_dir.mkdir(parents=True, exist_ok=True)
    overlays_dir.mkdir(parents=True, exist_ok=True)

    sam_model_registry, SamPredictor = import_samhq()

    device = args.device
    if device == "cuda" and not torch.cuda.is_available():
        print("[WARN] CUDA requested but not available. Falling back to CPU.")
        device = "cpu"

    print(f"[INFO] detections_json: {detections_json}")
    print(f"[INFO] sam_checkpoint: {sam_checkpoint}")
    print(f"[INFO] model_type: {args.model_type}")
    print(f"[INFO] output_dir: {output_dir}")
    print(f"[INFO] device: {device}")

    print("[INFO] Loading SAM-HQ model...")
    sam = sam_model_registry[args.model_type](checkpoint=str(sam_checkpoint))
    sam.to(device=device)
    predictor = SamPredictor(sam)

    detections_data = load_json(detections_json)

    results: dict[str, Any] = {
        "task": "segment_garments_samhq",
        "detections_json": str(detections_json),
        "sam_checkpoint": str(sam_checkpoint),
        "model_type": args.model_type,
        "device": device,
        "images": [],
    }

    images = detections_data.get("images", [])

    for image_idx, image_record in enumerate(images, start=1):
        image_path = Path(image_record["image_path"])
        print(f"[{image_idx:04d}/{len(images):04d}] {image_path}")

        image_bgr = cv2.imread(str(image_path))
        if image_bgr is None:
            print(f"[WARN] Failed to read image: {image_path}")
            continue

        height, width = image_bgr.shape[:2]
        image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)

        predictor.set_image(image_rgb)

        overlay = image_bgr.copy()
        image_segments: list[dict[str, Any]] = []

        detections = image_record.get("detections", [])

        for det in detections:
            det_id = int(det["det_id"])
            class_name = str(det["class_name"])
            confidence = float(det["confidence"])
            bbox_xyxy = [float(v) for v in det["bbox_xyxy"]]

            area = bbox_area_xyxy(bbox_xyxy)
            if area < args.min_box_area:
                print(
                    f"[WARN] Skip tiny box: image={image_path.name}, "
                    f"det_id={det_id}, area={area:.2f}"
                )
                continue

            box_np = clip_box_xyxy(bbox_xyxy, width=width, height=height)

            try:
                masks, scores, logits = predictor.predict(
                    point_coords=None,
                    point_labels=None,
                    box=box_np,
                    multimask_output=args.multimask_output,
                )
            except TypeError:
                # Some SAM-HQ forks use a slightly different signature.
                masks, scores, logits = predictor.predict(
                    box=box_np,
                    multimask_output=args.multimask_output,
                )

            best_mask, sam_score, best_mask_idx = get_best_mask(masks, scores)
            mask_bool = best_mask.astype(bool)
            mask_u8 = ensure_uint8_mask(mask_bool)

            mask_name = f"{image_path.stem}_det{det_id:03d}_{class_name}_mask.png"
            mask_path = masks_dir / mask_name
            cv2.imwrite(str(mask_path), mask_u8)

            color = CLASS_COLORS_BGR.get(class_name, (0, 255, 255))
            overlay = apply_mask_overlay(
                overlay=overlay,
                mask_bool=mask_bool,
                color_bgr=color,
                alpha=args.mask_alpha,
            )

            label = f"{class_name} {confidence:.2f}"
            draw_box_label(
                image=overlay,
                bbox_xyxy=bbox_xyxy,
                label=label,
                color=color,
            )

            mask_area = int(mask_bool.sum())

            segment_record = {
                "det_id": det_id,
                "class_id": int(det["class_id"]),
                "class_name": class_name,
                "confidence": confidence,
                "bbox_xyxy": bbox_xyxy,
                "bbox_format": "xyxy_abs_pixels",
                "mask_path": str(mask_path),
                "mask_area": mask_area,
                "sam_score": sam_score,
                "sam_best_mask_idx": best_mask_idx,
                "image_width": width,
                "image_height": height,
            }
            image_segments.append(segment_record)

        overlay_path = overlays_dir / f"{image_path.stem}_samhq_overlay.jpg"
        cv2.imwrite(str(overlay_path), overlay)

        result_image_record = {
            "image_id": image_record.get("image_id"),
            "image_path": str(image_path),
            "file_name": image_path.name,
            "width": width,
            "height": height,
            "num_detections": len(detections),
            "num_segments": len(image_segments),
            "overlay_path": str(overlay_path),
            "segments": image_segments,
        }
        results["images"].append(result_image_record)

    output_json = output_dir / "segmentation_results.json"
    save_json(results, output_json)

    print("[INFO] SAM-HQ segmentation finished.")
    print(f"[INFO] Results JSON: {output_json}")
    print(f"[INFO] Masks dir: {masks_dir}")
    print(f"[INFO] Overlays dir: {overlays_dir}")


def main() -> None:
    args = parse_args()
    run(args)


if __name__ == "__main__":
    main()
