from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import cv2


REGION_COLORS = {
    "collar": (255, 128, 0),      # blue-ish orange in BGR
    "sleeve": (255, 0, 255),      # magenta
    "hem": (0, 200, 255),         # yellow/orange
    "waist": (0, 0, 255),         # red
    "pant_leg": (0, 255, 0),      # green
    "unknown": (180, 180, 180),   # gray
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Visualize region crop boxes on original images for debugging. "
            "Reads region_crops.json generated by crop_garment_regions_from_landmarks.py."
        )
    )

    parser.add_argument(
        "--region-crops-json",
        type=str,
        required=True,
        help="Path to region_crops.json.",
    )

    parser.add_argument(
        "--output-dir",
        type=str,
        required=True,
        help="Output directory for debug visualization images.",
    )

    parser.add_argument(
        "--only-fallback",
        action="store_true",
        help="Only visualize records where fallback=true.",
    )

    parser.add_argument(
        "--only-landmark-region",
        action="store_true",
        help="Only visualize records where source=landmark_region.",
    )

    parser.add_argument(
        "--regions",
        nargs="*",
        default=None,
        help="Optional region filter, e.g. --regions waist hem.",
    )

    parser.add_argument(
        "--classes",
        nargs="*",
        default=None,
        help=(
            "Optional class filter, e.g. "
            "--classes trousers shorts skirt 'short sleeve top'."
        ),
    )

    parser.add_argument(
        "--max-images",
        type=int,
        default=0,
        help="Maximum number of original images to visualize. 0 means all.",
    )

    parser.add_argument(
        "--max-records",
        type=int,
        default=0,
        help="Maximum number of crop records to use before grouping. 0 means all.",
    )

    parser.add_argument(
        "--line-thickness",
        type=int,
        default=2,
        help="Rectangle line thickness.",
    )

    parser.add_argument(
        "--draw-index-list",
        action="store_true",
        help="Draw landmark index list in label text.",
    )

    parser.add_argument(
        "--save-flat",
        action="store_true",
        help=(
            "Save all visualizations directly under output dir. "
            "By default, images are grouped by region/source filters in filename only."
        ),
    )

    return parser.parse_args()


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def normalize_records(data: Any) -> List[Dict[str, Any]]:
    """
    Supports either:
    1. a list of records
    2. a dict with key 'records'
    3. a dict with key 'crops'
    """
    if isinstance(data, list):
        return data

    if isinstance(data, dict):
        for key in ["records", "crops", "region_crops"]:
            value = data.get(key)
            if isinstance(value, list):
                return value

    raise ValueError(
        "Unsupported region_crops.json format. "
        "Expected a list or a dict containing 'records'/'crops'/'region_crops'."
    )


def get_record_image_path(record: Dict[str, Any]) -> Optional[str]:
    for key in ["image_path", "image", "original_image_path", "source_image"]:
        value = record.get(key)
        if value:
            return str(value)
    return None


def get_record_bbox(record: Dict[str, Any]) -> Optional[Tuple[int, int, int, int]]:
    """
    Expected bbox key:
    bbox_xyxy: [x1, y1, x2, y2]
    """
    bbox = record.get("bbox_xyxy")
    if bbox is None:
        bbox = record.get("crop_bbox_xyxy")
    if bbox is None:
        bbox = record.get("box")

    if not bbox or len(bbox) != 4:
        return None

    x1, y1, x2, y2 = bbox
    return int(round(x1)), int(round(y1)), int(round(x2)), int(round(y2))


def as_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.lower() in ["true", "1", "yes", "y"]
    return bool(value)


def filter_records(
    records: List[Dict[str, Any]],
    only_fallback: bool = False,
    only_landmark_region: bool = False,
    regions: Optional[List[str]] = None,
    classes: Optional[List[str]] = None,
    max_records: int = 0,
) -> List[Dict[str, Any]]:
    region_set = set(regions) if regions else None
    class_set = set(classes) if classes else None

    filtered: List[Dict[str, Any]] = []

    for record in records:
        region = str(record.get("region", "unknown"))
        class_name = str(record.get("class_name", record.get("category", "unknown")))
        source = str(record.get("source", "unknown"))
        fallback = as_bool(record.get("fallback", False))

        if only_fallback and not fallback:
            continue

        if only_landmark_region and source != "landmark_region":
            continue

        if region_set is not None and region not in region_set:
            continue

        if class_set is not None and class_name not in class_set:
            continue

        filtered.append(record)

        if max_records > 0 and len(filtered) >= max_records:
            break

    return filtered


def group_records_by_image(records: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    grouped: Dict[str, List[Dict[str, Any]]] = defaultdict(list)

    for record in records:
        image_path = get_record_image_path(record)
        if not image_path:
            continue
        grouped[image_path].append(record)

    return dict(grouped)


def draw_dashed_rectangle(
    image,
    pt1: Tuple[int, int],
    pt2: Tuple[int, int],
    color: Tuple[int, int, int],
    thickness: int = 2,
    dash_length: int = 10,
) -> None:
    x1, y1 = pt1
    x2, y2 = pt2

    # top and bottom
    for x in range(x1, x2, dash_length * 2):
        cv2.line(image, (x, y1), (min(x + dash_length, x2), y1), color, thickness)
        cv2.line(image, (x, y2), (min(x + dash_length, x2), y2), color, thickness)

    # left and right
    for y in range(y1, y2, dash_length * 2):
        cv2.line(image, (x1, y), (x1, min(y + dash_length, y2)), color, thickness)
        cv2.line(image, (x2, y), (x2, min(y + dash_length, y2)), color, thickness)


def put_label(
    image,
    text: str,
    x: int,
    y: int,
    color: Tuple[int, int, int],
    font_scale: float = 0.45,
    thickness: int = 1,
) -> None:
    h, w = image.shape[:2]

    x = max(0, min(x, w - 1))
    y = max(15, min(y, h - 1))

    font = cv2.FONT_HERSHEY_SIMPLEX
    text_size, baseline = cv2.getTextSize(text, font, font_scale, thickness)

    text_w, text_h = text_size
    bg_x1 = x
    bg_y1 = max(0, y - text_h - baseline - 4)
    bg_x2 = min(w - 1, x + text_w + 4)
    bg_y2 = min(h - 1, y + baseline + 2)

    cv2.rectangle(image, (bg_x1, bg_y1), (bg_x2, bg_y2), (0, 0, 0), -1)
    cv2.putText(
        image,
        text,
        (x + 2, y - 2),
        font,
        font_scale,
        color,
        thickness,
        cv2.LINE_AA,
    )


def safe_filename_from_image_path(image_path: str) -> str:
    p = Path(image_path)
    stem = p.stem
    suffix = p.suffix if p.suffix else ".jpg"
    return f"{stem}_crop_debug{suffix}"


def visualize_one_image(
    image_path: str,
    records: List[Dict[str, Any]],
    output_path: Path,
    line_thickness: int = 2,
    draw_index_list: bool = False,
) -> bool:
    image = cv2.imread(image_path)
    if image is None:
        print(f"[WARN] Failed to read image: {image_path}")
        return False

    h, w = image.shape[:2]

    # Draw title
    title = f"{Path(image_path).name} | records={len(records)}"
    put_label(image, title, 8, 22, (255, 255, 255), font_scale=0.6, thickness=1)

    for i, record in enumerate(records):
        bbox = get_record_bbox(record)
        if bbox is None:
            print(f"[WARN] Missing bbox in record: {record}")
            continue

        x1, y1, x2, y2 = bbox

        # Clamp to image
        x1 = max(0, min(x1, w - 1))
        y1 = max(0, min(y1, h - 1))
        x2 = max(0, min(x2, w - 1))
        y2 = max(0, min(y2, h - 1))

        if x2 <= x1 or y2 <= y1:
            continue

        region = str(record.get("region", "unknown"))
        class_name = str(record.get("class_name", record.get("category", "unknown")))
        source = str(record.get("source", "unknown"))
        fallback = as_bool(record.get("fallback", False))
        det_id = record.get("det_id", record.get("instance_id", "?"))

        num_lm = record.get("num_landmarks", "?")
        num_rel = record.get("num_reliable_landmarks", "?")

        color = REGION_COLORS.get(region, REGION_COLORS["unknown"])

        # fallback: red dashed box
        # landmark_region: colored solid box
        if fallback:
            draw_dashed_rectangle(
                image,
                (x1, y1),
                (x2, y2),
                (0, 0, 255),
                thickness=line_thickness,
                dash_length=10,
            )
        else:
            cv2.rectangle(
                image,
                (x1, y1),
                (x2, y2),
                color,
                thickness=line_thickness,
            )

        label = (
            f"{i}:{region} | {class_name} | det={det_id} | "
            f"{source} | rel={num_rel}/{num_lm}"
        )

        if fallback:
            label += " | FB"

        if draw_index_list:
            rel_indices = record.get("reliable_landmark_indices", [])
            if rel_indices:
                label += f" | idx={rel_indices}"

        label_color = (0, 0, 255) if fallback else color

        label_y = y1 - 5
        if label_y < 20:
            label_y = y2 + 18

        put_label(
            image,
            label,
            x1,
            label_y,
            label_color,
            font_scale=0.45,
            thickness=1,
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    ok = cv2.imwrite(str(output_path), image)

    if not ok:
        print(f"[WARN] Failed to write image: {output_path}")
        return False

    return True


def main() -> None:
    args = parse_args()

    region_crops_json = Path(args.region_crops_json)
    output_dir = Path(args.output_dir)

    data = load_json(region_crops_json)
    records = normalize_records(data)

    print(f"[INFO] Loaded records: {len(records)}")

    filtered = filter_records(
        records=records,
        only_fallback=args.only_fallback,
        only_landmark_region=args.only_landmark_region,
        regions=args.regions,
        classes=args.classes,
        max_records=args.max_records,
    )

    print(f"[INFO] Filtered records: {len(filtered)}")

    grouped = group_records_by_image(filtered)
    image_items = list(grouped.items())

    if args.max_images > 0:
        image_items = image_items[: args.max_images]

    print(f"[INFO] Images to visualize: {len(image_items)}")

    output_dir.mkdir(parents=True, exist_ok=True)

    num_written = 0
    num_failed = 0

    for image_path, image_records in image_items:
        out_name = safe_filename_from_image_path(image_path)

        if args.only_fallback:
            out_name = out_name.replace("_crop_debug", "_fallback_crop_debug")

        if args.regions:
            region_tag = "-".join(args.regions)
            out_name = out_name.replace("_crop_debug", f"_{region_tag}_crop_debug")

        if args.classes:
            class_tag = "-".join([c.replace(" ", "_") for c in args.classes])
            out_name = out_name.replace("_crop_debug", f"_{class_tag}_crop_debug")

        output_path = output_dir / out_name

        ok = visualize_one_image(
            image_path=image_path,
            records=image_records,
            output_path=output_path,
            line_thickness=args.line_thickness,
            draw_index_list=args.draw_index_list,
        )

        if ok:
            num_written += 1
        else:
            num_failed += 1

    summary = {
        "region_crops_json": str(region_crops_json),
        "output_dir": str(output_dir),
        "total_records": len(records),
        "filtered_records": len(filtered),
        "num_images": len(image_items),
        "num_written": num_written,
        "num_failed": num_failed,
        "filters": {
            "only_fallback": args.only_fallback,
            "only_landmark_region": args.only_landmark_region,
            "regions": args.regions,
            "classes": args.classes,
            "max_images": args.max_images,
            "max_records": args.max_records,
        },
    }

    summary_path = output_dir / "debug_viz_summary.json"
    with summary_path.open("w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    print(f"[INFO] Written visualizations: {num_written}")
    print(f"[INFO] Failed visualizations: {num_failed}")
    print(f"[INFO] Summary saved to: {summary_path}")


if __name__ == "__main__":
    main()
